version: '3'

services:
  api:
    build: ./api
    image: api:latest
    container_name: api
    environment:
      PORT: 80
      DB_PORT: 5432
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      MEDIA_SERVER_ENDPOINT: http://media:80
      NODE_ENV: production
    command: sh -c "
        ./wait-for -t 60 db:5432
        && ./wait-for -t 60 media:80
        && npm run migration:run
        && npm start"
    volumes:
      - "./log:/app/.log"

  media:
    build: ./media
    image: media:latest
    container_name: media
    environment:
      PORT: 80
    volumes:
      - "mediadata:/app/static"

  chat:
    build: ./chat
    image: chat:latest
    container_name: chat
    environment:
      PORT: 80
      JWT_SECRET: ${JWT_SECRET}
      MAX_MESSAGES_LENGTH: 30

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  server:
    image: nginx:alpine
    container_name: server
    ports:
      - "8080:80"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"

volumes:
  dbdata:
  mediadata:
